### ISSUE TITLE
LoadError: cannot load such file -- factory_bot/awesome_linter

### ISSUE THREAD

**Issue by JoaoFagundes** [inkstak/factory_bot-awesome_linter#1]
Hey, I was trying to install the gem in our project and followed the instructions in the readme, but I get an `LoadError: cannot load such file -- factory_bot/awesome_linter` when trying to run the rake task. 

I commented out the `require "factory_bot/awesome_linter"` line in the rake task and then it worked, but wanted to flag this here to make sure this is the expected behavior, and if the require is not necessary I'd be happy to remove that line from the rake task

**Comment by inkstak** [comment]
You're right, the example is wrong.
We didn't use the line `require "factory_bot/awesome_linter"` in any of out apps.
Thanks for pointing it.
